#!/bin/bash
# Краткий перечень команд для работы с Docker Registry, GitHub и Rollback'ами

echo "🚀 Agri Platform - Docker Registry & Rollback Manager"
echo ""
echo "════════════════════════════════════════════════════════"
echo "📦 СБОРКА И ОТПРАВКА (Docker Registry + GitHub)"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Собрать версию и отправить в реестр + GitHub:"
echo "  ./build-and-push.sh 1.0.0 scamlux3221"
echo ""
echo "════════════════════════════════════════════════════════"
echo "🚀 РАЗВЁРТЫВАНИЕ"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Развернуть версию 1.0.0:"
echo "  TAG=1.0.0 ./start.sh local"
echo ""
echo "Развернуть latest версию:"
echo "  ./start.sh local"
echo ""
echo "════════════════════════════════════════════════════════"
echo "⏮️ ROLLBACK УПРАВЛЕНИЕ"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Посмотреть доступные версии:"
echo "  ./rollback.sh list"
echo ""
echo "Откатиться на версию 1.0.0:"
echo "  ./rollback.sh deploy 1.0.0"
echo ""
echo "Текущая версия:"
echo "  ./rollback.sh current"
echo ""
echo "Сравнить версии:"
echo "  ./rollback.sh compare 1.0.0 1.0.1"
echo ""
echo "════════════════════════════════════════════════════════"
echo "🌐 ДОСТУП К ПРИЛОЖЕНИЮ"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Web App:    http://localhost:3000"
echo "API:        http://localhost:8000"
echo "Swagger:    http://localhost:8080"
echo "Grafana:    http://localhost:3001 (admin/admin)"
echo "Prometheus: http://localhost:9090"
echo ""
echo "════════════════════════════════════════════════════════"
echo "📚 ДОКУМЕНТАЦИЯ"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Быстрый старт:"
echo "  cat QUICKSTART.md"
echo ""
echo "Настройка Git & GitHub:"
echo "  cat GIT_SETUP.md"
echo ""
